name: recharts_flutter
description: Recharts-style charting library for Flutter.
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
